/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.100
 * Generated at: 2024-04-29 06:18:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Locale;
import java.text.NumberFormat;
import java.util.Map;
import java.util.HashMap;
import java.util.ArrayList;
import java.util.List;
import java.util.Date;
import java.text.SimpleDateFormat;
import store.DAO.OrderDAO;
import store.DTO.Order;
import store.Service.OrderServiceImpl;
import store.Service.OrderService;

public final class owner_005fpanel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/BYJ/JSP/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/Main/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/sql.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1712913999052L));
    _jspx_dependants.put("jar:file:/D:/BYJ/JSP/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/Main/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/D:/BYJ/JSP/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/Main/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/D:/BYJ/JSP/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/Main/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(12);
    _jspx_imports_classes.add("store.DTO.Order");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("store.Service.OrderService");
    _jspx_imports_classes.add("java.util.Locale");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("store.DAO.OrderDAO");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("java.text.NumberFormat");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("store.Service.OrderServiceImpl");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencyCode_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencyCode_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencyCode_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

if (session != null && session.getAttribute("loginId") != null) {

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\" data-bs-theme=\"auto\">\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"static/js/color-modes.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.js\" integrity=\"sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css\" />\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.13.1/jquery-ui.js\"></script>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>panel_test</title>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/@docsearch/css@3\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"static/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"static/css/sign-in.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"static/css/headers.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"static/css/grid.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"static/css/chat.css\">\r\n");
      out.write("<style>\r\n");
      out.write(".bd-placeholder-img {\r\n");
      out.write("	font-size: 1.125rem;\r\n");
      out.write("	text-anchor: middle;\r\n");
      out.write("	-webkit-user-select: none;\r\n");
      out.write("	-moz-user-select: none;\r\n");
      out.write("	user-select: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( min-width : 768px) {\r\n");
      out.write("	.bd-placeholder-img-lg {\r\n");
      out.write("		font-size: 3.5rem;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".b-example-divider {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 3rem;\r\n");
      out.write("	background-color: rgba(0, 0, 0, .1);\r\n");
      out.write("	border: solid rgba(0, 0, 0, .15);\r\n");
      out.write("	border-width: 1px 0;\r\n");
      out.write("	box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em\r\n");
      out.write("		rgba(0, 0, 0, .15);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".b-example-vr {\r\n");
      out.write("	flex-shrink: 0;\r\n");
      out.write("	width: 1.5rem;\r\n");
      out.write("	height: 100vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bi {\r\n");
      out.write("	vertical-align: -.125em;\r\n");
      out.write("	fill: currentColor;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-scroller {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	z-index: 2;\r\n");
      out.write("	height: 2.75rem;\r\n");
      out.write("	overflow-y: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-scroller .nav {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-wrap: nowrap;\r\n");
      out.write("	padding-bottom: 1rem;\r\n");
      out.write("	margin-top: -1px;\r\n");
      out.write("	overflow-x: auto;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("	-webkit-overflow-scrolling: touch;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-bd-primary {\r\n");
      out.write("	--bd-violet-bg: #712cf9;\r\n");
      out.write("	--bd-violet-rgb: 112.520718, 44.062154, 249.437846;\r\n");
      out.write("	--bs-btn-font-weight: 600;\r\n");
      out.write("	--bs-btn-color: var(--bs-white);\r\n");
      out.write("	--bs-btn-bg: var(--bd-violet-bg);\r\n");
      out.write("	--bs-btn-border-color: var(--bd-violet-bg);\r\n");
      out.write("	--bs-btn-hover-color: var(--bs-white);\r\n");
      out.write("	--bs-btn-hover-bg: #6528e0;\r\n");
      out.write("	--bs-btn-hover-border-color: #6528e0;\r\n");
      out.write("	--bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);\r\n");
      out.write("	--bs-btn-active-color: var(--bs-btn-hover-color);\r\n");
      out.write("	--bs-btn-active-bg: #5a23c8;\r\n");
      out.write("	--bs-btn-active-border-color: #5a23c8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bd-mode-toggle {\r\n");
      out.write("	z-index: 1500;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bd-mode-toggle .dropdown-menu .active .bi {\r\n");
      out.write("	display: block !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".outer-card {\r\n");
      out.write("	background-color: black;\r\n");
      out.write("	color: white;\r\n");
      out.write("	border-radius: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".inner-card {\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".inner-card .card-body {\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 내용을 화면에 꽉 차게 만듭니다. */\r\n");
      out.write("html, body, .container, .row, .col-md-4 {\r\n");
      out.write("	height: 80%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 네비게이션 바 스타일링 */\r\n");
      out.write(".navbar {\r\n");
      out.write("	margin-bottom: 20px; /* 네비게이션 바 아래 여백 추가 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 카드 푸터 스타일링 */\r\n");
      out.write(".card-footer-custom {\r\n");
      out.write("	background-color: transparent;\r\n");
      out.write("	border: none;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-custom {\r\n");
      out.write("	margin-left: auto;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<svg xmlns=\"http://www.w3.org/2000/svg\" class=\"d-none\">\r\n");
      out.write("      <symbol id=\"check2\" viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol id=\"circle-half\" viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol id=\"moon-stars-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z\" />\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol id=\"sun-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("    </svg>\r\n");
      out.write("\r\n");
      out.write("	<div\r\n");
      out.write("		class=\"dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle\">\r\n");
      out.write("		<button\r\n");
      out.write("			class=\"btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center\"\r\n");
      out.write("			id=\"bd-theme\" type=\"button\" aria-expanded=\"false\"\r\n");
      out.write("			data-bs-toggle=\"dropdown\" aria-label=\"Toggle theme (auto)\">\r\n");
      out.write("			<svg class=\"bi my-1 theme-icon-active\" width=\"1em\" height=\"1em\">\r\n");
      out.write("				<use href=\"#circle-half\"></use></svg>\r\n");
      out.write("			<span class=\"visually-hidden\" id=\"bd-theme-text\">Toggle theme</span>\r\n");
      out.write("		</button>\r\n");
      out.write("		<ul class=\"dropdown-menu dropdown-menu-end shadow\"\r\n");
      out.write("			aria-labelledby=\"bd-theme-text\">\r\n");
      out.write("			<li>\r\n");
      out.write("				<button type=\"button\"\r\n");
      out.write("					class=\"dropdown-item d-flex align-items-center\"\r\n");
      out.write("					data-bs-theme-value=\"light\" aria-pressed=\"false\">\r\n");
      out.write("					<svg class=\"bi me-2 opacity-50\" width=\"1em\" height=\"1em\">\r\n");
      out.write("						<use href=\"#sun-fill\"></use></svg>\r\n");
      out.write("					Light\r\n");
      out.write("					<svg class=\"bi ms-auto d-none\" width=\"1em\" height=\"1em\">\r\n");
      out.write("						<use href=\"#check2\"></use></svg>\r\n");
      out.write("				</button>\r\n");
      out.write("			</li>\r\n");
      out.write("			<li>\r\n");
      out.write("				<button type=\"button\"\r\n");
      out.write("					class=\"dropdown-item d-flex align-items-center\"\r\n");
      out.write("					data-bs-theme-value=\"dark\" aria-pressed=\"false\">\r\n");
      out.write("					<svg class=\"bi me-2 opacity-50\" width=\"1em\" height=\"1em\">\r\n");
      out.write("						<use href=\"#moon-stars-fill\"></use></svg>\r\n");
      out.write("					Dark\r\n");
      out.write("					<svg class=\"bi ms-auto d-none\" width=\"1em\" height=\"1em\">\r\n");
      out.write("						<use href=\"#check2\"></use></svg>\r\n");
      out.write("				</button>\r\n");
      out.write("			</li>\r\n");
      out.write("			<li>\r\n");
      out.write("				<button type=\"button\"\r\n");
      out.write("					class=\"dropdown-item d-flex align-items-center active\"\r\n");
      out.write("					data-bs-theme-value=\"auto\" aria-pressed=\"true\">\r\n");
      out.write("					<svg class=\"bi me-2 opacity-50\" width=\"1em\" height=\"1em\">\r\n");
      out.write("						<use href=\"#circle-half\"></use></svg>\r\n");
      out.write("					Auto\r\n");
      out.write("					<svg class=\"bi ms-auto d-none\" width=\"1em\" height=\"1em\">\r\n");
      out.write("						<use href=\"#check2\"></use></svg>\r\n");
      out.write("				</button>\r\n");
      out.write("			</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<svg xmlns=\"http://www.w3.org/2000/svg\" class=\"d-none\">\r\n");
      out.write("  <symbol id=\"bootstrap\" viewBox=\"0 0 118 94\">\r\n");
      out.write("    <title>Bootstrap</title>\r\n");
      out.write("    <path fill-rule=\"evenodd\" clip-rule=\"evenodd\"\r\n");
      out.write("			d=\"M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z\"></path>\r\n");
      out.write("  </symbol>\r\n");
      out.write("  <symbol id=\"home\" viewBox=\"0 0 16 16\">\r\n");
      out.write("    <path\r\n");
      out.write("			d=\"M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5z\" />\r\n");
      out.write("  </symbol>\r\n");
      out.write("  <symbol id=\"speedometer2\" viewBox=\"0 0 16 16\">\r\n");
      out.write("    <path\r\n");
      out.write("			d=\"M8 4a.5.5 0 0 1 .5.5V6a.5.5 0 0 1-1 0V4.5A.5.5 0 0 1 8 4zM3.732 5.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707zM2 10a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 10zm9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5zm.754-4.246a.389.389 0 0 0-.527-.02L7.547 9.31a.91.91 0 1 0 1.302 1.258l3.434-4.297a.389.389 0 0 0-.029-.518z\" />\r\n");
      out.write("    <path fill-rule=\"evenodd\"\r\n");
      out.write("			d=\"M0 10a8 8 0 1 1 15.547 2.661c-.442 1.253-1.845 1.602-2.932 1.25C11.309 13.488 9.475 13 8 13c-1.474 0-3.31.488-4.615.911-1.087.352-2.49.003-2.932-1.25A7.988 7.988 0 0 1 0 10zm8-7a7 7 0 0 0-6.603 9.329c.203.575.923.876 1.68.63C4.397 12.533 6.358 12 8 12s3.604.532 4.923.96c.757.245 1.477-.056 1.68-.631A7 7 0 0 0 8 3z\" />\r\n");
      out.write("  </symbol>\r\n");
      out.write("  <symbol id=\"table\" viewBox=\"0 0 16 16\">\r\n");
      out.write("    <path\r\n");
      out.write("			d=\"M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm15 2h-4v3h4V4zm0 4h-4v3h4V8zm0 4h-4v3h3a1 1 0 0 0 1-1v-2zm-5 3v-3H6v3h4zm-5 0v-3H1v2a1 1 0 0 0 1 1h3zm-4-4h4V8H1v3zm0-4h4V4H1v3zm5-3v3h4V4H6zm4 4H6v3h4V8z\" />\r\n");
      out.write("  </symbol>\r\n");
      out.write("  <symbol id=\"people-circle\" viewBox=\"0 0 16 16\">\r\n");
      out.write("    <path d=\"M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z\" />\r\n");
      out.write("    <path fill-rule=\"evenodd\"\r\n");
      out.write("			d=\"M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z\" />\r\n");
      out.write("  </symbol>\r\n");
      out.write("  <symbol id=\"grid\" viewBox=\"0 0 16 16\">\r\n");
      out.write("    <path\r\n");
      out.write("			d=\"M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zM2.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zM1 10.5A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z\" />\r\n");
      out.write("  </symbol>\r\n");
      out.write("</svg>\r\n");
      out.write("\r\n");
      out.write("	");

		List<Order> orders = new ArrayList<>();
	
		// 테이블 리스트
		// 	    List<List<?>> tableList = new ArrayList<>();
		Map<Integer, List<?>> tableMap = new HashMap<>();
		// 	    List<List<?>> tableList = new ArrayList<>();
	
		OrderDAO orderDAO = new OrderDAO();
		int table_sz = 6;
		for (int i = 0; i < table_sz; i++) {
			// 자바 문법에 맞게 추가
			orders = orderDAO.list(i + 1);
	
			if (orders != null) {
				// 	        	tableList.add(i, orders);
				tableMap.put(i + 1, orders);
			}
		}
	
		// 	    pageContext.setAttribute("tableList", tableList);
		pageContext.setAttribute("tableMap", tableMap);
		
		// 오늘 날짜 가져오기
		java.util.Date utilDate = new java.util.Date();
		java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
		String todayStr = sdf.format(utilDate);
		//request.setAttribute("todayStr", todayStr);
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg bg-body-tertiary\">\r\n");
      out.write("		<div class=\"container-fluid\">\r\n");
      out.write("			<a class=\"navbar-brand me-5\">냉면집 QR 주문 전체 관리</a>\r\n");
      out.write("			<button class=\"navbar-toggler\" type=\"button\"\r\n");
      out.write("				data-bs-toggle=\"collapse\" data-bs-target=\"#navbarToggler\"\r\n");
      out.write("				aria-controls=\"navbarToggler\" aria-expanded=\"false\"\r\n");
      out.write("				aria-label=\"Toggle navigation\">\r\n");
      out.write("				<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("			</button>\r\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"navbarToggler\">\r\n");
      out.write("				<ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("					<li class=\"nav-item\">\r\n");
      out.write("						<button id=\"salesBtn\" class=\"btn btn-lg btn-dark ms-3 me-3\" type=\"button\">매출 관리</button>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"nav-item\">\r\n");
      out.write("						<button id=\"cancelBtn\" class=\"btn btn-lg btn-dark ms-3\" type=\"button\">주문 취소</button>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"nav-item\">\r\n");
      out.write("						<button id=\"addMenuBtn\" class=\"btn btn-lg btn-dark ms-3\" type=\"button\">메뉴 추가</button>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("	 $('#addMenuBtn').click(function() {\r\n");
      out.write("	        window.location.href = \"addMenu.jsp\"; // 페이지 이동을 위해 'location'을 사용\r\n");
      out.write("     });\r\n");
      out.write("  	</script>\r\n");
      out.write("	<!-- 매출 관리 모달 창 -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog modal-lg\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\">매출 관리</h5>\r\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("				<!-- 날짜 선택기 -->\r\n");
      out.write("                <label for=\"selectedDate\">날짜 선택:</label>\r\n");
      out.write("                <input type=\"text\" id=\"selectedDate\" name=\"selectedDate\">\r\n");
      out.write("			<table class=\"table\">\r\n");
      out.write("        		<tbody id=\"salesTableBody\">\r\n");
      out.write("\r\n");
      out.write("<!-- 				    <tr> -->\r\n");
      out.write("\r\n");
      out.write("<!-- 				        <td> -->\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!-- 				        </td> -->\r\n");
      out.write("<!-- 				    </tr> -->\r\n");
      out.write("\r\n");
      out.write("        		</tbody>\r\n");
      out.write("    		</table>\r\n");
      out.write("<!--     		<p>해당일 총 매출:  -->\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!-- 			</p> -->\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">닫기</button>\r\n");
      out.write("					<!-- 다른 버튼 등을 추가할 수 있습니다. -->\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	    // 매출 관리 버튼 클릭 시 모달 띄우기\r\n");
      out.write("	    $('#salesBtn').click(function() {\r\n");
      out.write("	   		 // 모달 띄우기\r\n");
      out.write("	    	$('#myModal').modal('show');\r\n");
      out.write("	    });\r\n");
      out.write("	    \r\n");
      out.write("	    $(document).ready(function() {\r\n");
      out.write("	        $('#selectedDate').datepicker({\r\n");
      out.write("	            dateFormat: 'yy-mm-dd',\r\n");
      out.write("	            onSelect: function(dateText, inst) {\r\n");
      out.write("	                console.log('날짜 선택됨:', dateText);\r\n");
      out.write("	                $.ajax({\r\n");
      out.write("	                    url: '/Main/orderServlet',\r\n");
      out.write("	                    method: 'POST',\r\n");
      out.write("	                    data: { selectedDate: dateText },\r\n");
      out.write("	                    success: function(response) {\r\n");
      out.write("	                        // 서버에서 받은 HTML 형식의 응답을 테이블에 삽입\r\n");
      out.write("	                        $('#salesTableBody').html(response);\r\n");
      out.write("	                    },\r\n");
      out.write("	                    error: function(xhr, status, error) {\r\n");
      out.write("	                        console.error('서버 오류:', error);\r\n");
      out.write("	                    }\r\n");
      out.write("	                });\r\n");
      out.write("	            }\r\n");
      out.write("	        });\r\n");
      out.write("	    });\r\n");
      out.write("	    \r\n");
      out.write("	    $.datepicker.setDefaults({\r\n");
      out.write("	        closeText: \"닫기\",\r\n");
      out.write("	        currentText: \"오늘\",\r\n");
      out.write("	        prevText: '이전 달',\r\n");
      out.write("	        nextText: '다음 달',\r\n");
      out.write("	        monthNames: ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],\r\n");
      out.write("	        monthNamesShort: ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],\r\n");
      out.write("	        dayNames: ['일', '월', '화', '수', '목', '금', '토'],\r\n");
      out.write("	        dayNamesShort: ['일', '월', '화', '수', '목', '금', '토'],\r\n");
      out.write("	        dayNamesMin: ['일', '월', '화', '수', '목', '금', '토'],\r\n");
      out.write("	        weekHeader: \"주\",\r\n");
      out.write("	        yearSuffix: '년'\r\n");
      out.write("	        }); \r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	<!-- 주문 취소 모달 -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"cancelModal\" tabindex=\"-1\" aria-hidden=\"true\">\r\n");
      out.write("	    <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("	        <div class=\"modal-content\">\r\n");
      out.write("	            <div class=\"modal-header\">\r\n");
      out.write("	                <h5 class=\"modal-title\">주문 취소</h5>\r\n");
      out.write("	                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"modal-body\">\r\n");
      out.write("				    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("	            <div class=\"modal-footer\">\r\n");
      out.write("	                <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">닫기</button>\r\n");
      out.write("	                <!-- 다른 버튼 등을 추가할 수 있습니다. -->\r\n");
      out.write("	            </div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script>\r\n");
      out.write("	// 2024-04-13 : 박은서 \r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("	    $('.cancel').click(function() {\r\n");
      out.write("	    	\r\n");
      out.write("	        var orderId = $(this).data('order-id');  // 버튼에서 order-id 데이터를 가져옵니다.\r\n");
      out.write("	        \r\n");
      out.write("	        // AJAX 요청을 서버에 보냅니다.\r\n");
      out.write("	        $.ajax({\r\n");
      out.write("	            url: 'deleteOrder.jsp',  // 요청을 처리할 서버의 URL\r\n");
      out.write("	            type: 'POST',            // 데이터를 서버로 보내는 방법\r\n");
      out.write("	            data: {orderNo: orderId},  // 서버로 보낼 데이터\r\n");
      out.write("	            success: function(response) {  // 요청이 성공적으로 완료되면 실행되는 함수\r\n");
      out.write("	                // alert('주문번호 ' + orderId + '가 성공적으로 취소되었습니다.');\r\n");
      out.write("	                window.location.reload();  // 페이지를 리로드하여 변경사항을 반영\r\n");
      out.write("	            },\r\n");
      out.write("	            error: function() {  // 요청이 실패하면 실행되는 함수\r\n");
      out.write("	                alert('주문 취소에 실패하였습니다.');\r\n");
      out.write("	            }\r\n");
      out.write("	        });\r\n");
      out.write("	    });\r\n");
      out.write("	});\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("    // 주문 취소 버튼 클릭 시 모달 띄우기\r\n");
      out.write("	    document.getElementById('cancelBtn').addEventListener('click', function() {\r\n");
      out.write("	        // 모달 띄우기\r\n");
      out.write("	        $('#cancelModal').modal('show');\r\n");
      out.write("	    });\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row justify-content-center align-items-center h-100\">\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("			");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		function completeOrder(tableNo) {\r\n");
      out.write("			// AJAX 요청 생성\r\n");
      out.write("			var xhr = new XMLHttpRequest();\r\n");
      out.write("			var url = \"submit_order.jsp\";\r\n");
      out.write("			var params = \"tableNo=\" + tableNo; // 요청 데이터\r\n");
      out.write("			xhr.open(\"POST\", url, true);\r\n");
      out.write("\r\n");
      out.write("			// 요청 헤더 설정\r\n");
      out.write("			xhr.setRequestHeader(\"Content-type\",\r\n");
      out.write("					\"application/x-www-form-urlencoded\");\r\n");
      out.write("\r\n");
      out.write("			// 서버 응답 처리\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				if (xhr.readyState === XMLHttpRequest.DONE) {\r\n");
      out.write("					if (xhr.status === 200) {\r\n");
      out.write("						// 서버 응답이 성공적으로 도착한 경우\r\n");
      out.write("						var response = JSON.parse(xhr.responseText);\r\n");
      out.write("						if (response.success) {\r\n");
      out.write("							alert(\"주문이 성공적으로 완료되었습니다.\");\r\n");
      out.write("							location.reload();\r\n");
      out.write("						} else {\r\n");
      out.write("							alert(\"주문 처리 중 오류가 발생했습니다.\");\r\n");
      out.write("						}\r\n");
      out.write("					} else {\r\n");
      out.write("						// 서버 응답이 실패한 경우\r\n");
      out.write("						alert(\"서버 오류: \" + xhr.status);\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("\r\n");
      out.write("			// AJAX 요청 전송\r\n");
      out.write("			xhr.send(params);\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("	<div class=\"order-summary\">\r\n");
      out.write("   \r\n");
      out.write("      <button id=\"chatButton\" class=\"chat-button\">채팅</button>\r\n");
      out.write("      \r\n");
      out.write("      <div id=\"chatWindow\" class=\"chat-window\" style=\"display: none;\">\r\n");
      out.write("         <div class=\"chat-header\">\r\n");
      out.write("              <span>채팅 창</span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- 채팅 내용이 여기 들어갑니다 -->\r\n");
      out.write("          <div id=\"chat-content\" class=\"chat-content\">\r\n");
      out.write("              <!-- 메세지들 -->\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- 메세지 입력 -->\r\n");
      out.write("          <div class=\"chat-input\">\r\n");
      out.write("              <input type=\"text\" id=\"messageInput\" placeholder=\"메세지 입력\" onkeypress=\"handleKeyPress(event)\">\r\n");
      out.write("              <button onclick=\"sendMessage()\">전송</button>\r\n");
      out.write("              <button onclick=\"toggleChatWindow()\">닫기</button>\r\n");
      out.write("          </div>\r\n");
      out.write("         \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("	<script>\r\n");
      out.write("	function toggleChatWindow() {\r\n");
      out.write("	    var chatWindow = document.getElementById(\"chatWindow\");\r\n");
      out.write("	    if (chatWindow.style.display === \"none\") {\r\n");
      out.write("	        chatWindow.style.display = \"block\";\r\n");
      out.write("	    } else {\r\n");
      out.write("	        chatWindow.style.display = \"none\";\r\n");
      out.write("	    }\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	document.getElementById(\"chatButton\").onclick = toggleChatWindow;\r\n");
      out.write("	\r\n");
      out.write("	var socket = new WebSocket(\"ws://localhost:9090/Main/chatting\");\r\n");
      out.write("	\r\n");
      out.write("	socket.onopen = function() {\r\n");
      out.write("	    console.log(\"WebSocket 연결 성공\");\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	// 페이지 로딩 시 로컬 스토리지에서 채팅 기록 불러오기\r\n");
      out.write("	document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("	    var chatArea = document.getElementById(\"chat-content\");\r\n");
      out.write("	    var chatHistory = localStorage.getItem(\"chatHistory\");\r\n");
      out.write("	    if (chatHistory) {\r\n");
      out.write("	        chatArea.innerHTML = chatHistory;\r\n");
      out.write("	    }\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	socket.onmessage = function(event) {\r\n");
      out.write("	    console.log(\"메시지 수신: \" + event.data);\r\n");
      out.write("	    var chatArea = document.getElementById(\"chat-content\");\r\n");
      out.write("	    chatArea.innerHTML += \"<div>\" + event.data + \"</div>\";\r\n");
      out.write("	    chatArea.scrollTop = chatArea.scrollHeight;\r\n");
      out.write("	};\r\n");
      out.write("	\r\n");
      out.write("	socket.onclose = function() {\r\n");
      out.write("	    console.log(\"WebSocket 연결 종료\");\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function sendMessage() {\r\n");
      out.write("	    var messageInput = document.getElementById(\"messageInput\");\r\n");
      out.write("	    var message = messageInput.value;\r\n");
      out.write("        var tableNum = \"사장님\"; // JSP Expression to get server-side variable\r\n");
      out.write("	    \r\n");
      out.write("	    socket.send(tableNum + \" : \" + message);\r\n");
      out.write("	    messageInput.value = \"\";\r\n");
      out.write("	    var chatArea = document.getElementById(\"chat-content\");\r\n");
      out.write("	    chatArea.scrollTop = chatArea.scrollHeight;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function handleKeyPress(event) {\r\n");
      out.write("	    if (event.keyCode === 13) {\r\n");
      out.write("	        sendMessage();\r\n");
      out.write("	    }\r\n");
      out.write("	}\r\n");
      out.write("	</script>\r\n");
      out.write("	<script src=\"static/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("	");

		} else {
		response.sendRedirect("OwnerLogin/login.jsp");
		}
	
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /owner_panel.jsp(423,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("table");
      // /owner_panel.jsp(423,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/owner_panel.jsp(423,8) '${tableMap}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${tableMap}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("				        <h4>테이블 번호: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${table.key}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h4>\r\n");
            out.write("				        <table class=\"table\">\r\n");
            out.write("				            <thead>\r\n");
            out.write("				                <tr>\r\n");
            out.write("				                    <th>주문 번호</th>\r\n");
            out.write("				                    <th>메뉴</th>\r\n");
            out.write("				                    <th>수량</th>\r\n");
            out.write("				                    <th>가격</th>\r\n");
            out.write("				                    <th>날짜</th>\r\n");
            out.write("				                    <th>주문 상태</th>\r\n");
            out.write("				                    <th>취소</th>\r\n");
            out.write("				                </tr>\r\n");
            out.write("				            </thead>\r\n");
            out.write("				            <tbody>\r\n");
            out.write("				                ");
            if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("				            </tbody>\r\n");
            out.write("				        </table>\r\n");
            out.write("				    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /owner_panel.jsp(438,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("order");
      // /owner_panel.jsp(438,20) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/owner_panel.jsp(438,20) '${table.value}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${table.value}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("				                    <tr>\r\n");
            out.write("				                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${order.order_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("				                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${order.menu_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("				                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${order.amount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("				                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${order.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("				                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${order.order_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("				                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${order.status}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("				                        <td>\r\n");
            out.write("				                            <button type=\"button\" class=\"btn btn-danger cancel\" id=\"btn-cancel\" data-order-id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${order.order_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">취소</button>\r\n");
            out.write("				                        </td>\r\n");
            out.write("				                    </tr>\r\n");
            out.write("				                ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /owner_panel.jsp(497,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("table");
      // /owner_panel.jsp(497,3) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/owner_panel.jsp(497,3) '${ tableMap }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ tableMap }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("				<div class=\"col-md-4 mb-4\">\r\n");
            out.write("					<div class=\"card outer-card\">\r\n");
            out.write("						<div class=\"card-body\">\r\n");
            out.write("							<h5 class=\"card-title\">테이블 ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ table.key }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h5>\r\n");
            out.write("							<!-- 내부 카드 -->\r\n");
            out.write("							<div class=\"card inner-card\">\r\n");
            out.write("								<div class=\"card-body\">\r\n");
            out.write("									");
            if (_jspx_meth_c_005fset_005f0(_jspx_th_c_005fforEach_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f2))
              return true;
            out.write("\r\n");
            out.write("									");
            if (_jspx_meth_c_005fforEach_005f3(_jspx_th_c_005fforEach_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f2))
              return true;
            out.write("\r\n");
            out.write("								</div>\r\n");
            out.write("								<div class=\"card-footer card-footer-custom\">\r\n");
            out.write("									<!-- 									<p class=\"text-dark mb-0 mr-auto\">￦</p> -->\r\n");
            out.write("									<p class=\"text-dark mb-0 mr-auto\">\r\n");
            out.write("										");
            if (_jspx_meth_fmt_005fformatNumber_005f1(_jspx_th_c_005fforEach_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f2))
              return true;
            out.write("\r\n");
            out.write("									</p>\r\n");
            out.write("									<button class=\"btn btn-dark btn-custom\"\r\n");
            out.write("										onclick=\"completeOrder('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ table.key }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("')\">완료</button>\r\n");
            out.write("								</div>\r\n");
            out.write("							</div>\r\n");
            out.write("							<!-- 내부 카드 끝 -->\r\n");
            out.write("						</div>\r\n");
            out.write("					</div>\r\n");
            out.write("				</div>\r\n");
            out.write("			");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f2)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f2);
      // /owner_panel.jsp(505,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("totalPrice");
      // /owner_panel.jsp(505,9) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/owner_panel.jsp(505,9) '0'",_jsp_getExpressionFactory().createValueExpression("0",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f2)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f3_reused = false;
    try {
      _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f2);
      // /owner_panel.jsp(506,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setVar("order");
      // /owner_panel.jsp(506,9) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setItems(new org.apache.jasper.el.JspValueExpression("/owner_panel.jsp(506,9) '${ table.value }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ table.value }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
        if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("										");
            out.write("\r\n");
            out.write("										");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f3, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f3))
              return true;
            out.write("\r\n");
            out.write("									");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f3);
      _jspx_th_c_005fforEach_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f3, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f3)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f3);
      // /owner_panel.jsp(508,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ order.status eq 'pay ok' || order.status eq 'PAY OK' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("											<div style=\"display: flex; justify-content: space-between;\">\r\n");
          out.write("												<p class=\"card-text text-dark\">\r\n");
          out.write("													<!-- 반복문으로 menu_name 같은게 나오면 name 중복 제거 후 amount 만큼 더해서 출력  -->\r\n");
          out.write("													");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ order.menu_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("												</p>\r\n");
          out.write("												");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ order.amount }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("개\r\n");
          out.write("												<p class=\"card-text text-dark\">\r\n");
          out.write("													");
          if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f3))
            return true;
          out.write("\r\n");
          out.write("												</p>\r\n");
          out.write("											</div>\r\n");
          out.write("\r\n");
          out.write("											<!-- <p class=\"card-text text-dark\">내용을 여기에 넣으세요.</p> -->\r\n");
          out.write("											<p style=\"display: none\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ totalPrice = Integer.parseInt(totalPrice) + order.price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("											</p>\r\n");
          out.write("										");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f3)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencyCode_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /owner_panel.jsp(516,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ order.price }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /owner_panel.jsp(516,13) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setType("currency");
      // /owner_panel.jsp(516,13) name = currencyCode type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setCurrencyCode("KRW");
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencyCode_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f2)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencyCode_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f2);
      // /owner_panel.jsp(529,10) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ totalPrice }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /owner_panel.jsp(529,10) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setType("currency");
      // /owner_panel.jsp(529,10) name = currencyCode type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setCurrencyCode("KRW");
      int _jspx_eval_fmt_005fformatNumber_005f1 = _jspx_th_fmt_005fformatNumber_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencyCode_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f1);
      _jspx_th_fmt_005fformatNumber_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f1_reused);
    }
    return false;
  }
}
